### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MazeChaZer** [celest-time/celest#1]
What is the license of this project?

**Comment by hanikesn** [comment]
As the project is a port of java.time it's licensed under the GPLv2 with the classpath expection. I'm curious if that would be a problem for you?

**Comment by MazeChaZer** [comment]
Thanks for the clarification. I want to use this library in a proprietary project and was worried about the virality of the GPL. Looking at the classpath exception clause this doesn't seem to be a problem.

It would be nice if this repository had a LICENSE file that clearly states the license of the whole project.

**Comment by hanikesn** [comment]
There's now a license file in the repo.
